---
- name: Start de orchestrator!
  hosts: localhost
  tasks:
    - pause:
        prompt: "Welkom bij de orchestrator van Michael Hajjar!\nde orchestrator is gemaakt voor VM2 en heeft als doel snel virtuele machines aanmaken, aanpassen of verwijderen.\nVoordat u een VM kunt aanvragen, hebben wij informatie nodig.\nVolg de wizard en vul de vragen in (het kan 10 minuten duren voordat een actie is uitgevoerd).\n\nBent u een bestaande klant of een nieuwe klant?\n \n- Bestaande klant (typ bestaand) \n- Nieuwe klant    (typ nieuw)\n"
      register: menu_klant

    - pause:
        prompt: "\nWat is uw voornaam?\n"
      register: menu_voornaam

    - pause:
        prompt: "\nWat is uw achternaam?\n"
      register: menu_achternaam

    - pause:
        prompt: "\nWat is uw bedrijfsnaam?\n"
      register: menu_bedrijfsnaam

    - pause:
        prompt: "Wat wilt u doen? \n\n- een VM aanmaken    (typ create) \n- een VM aanpassen   (typ modify) \n- een VM verwijderen (typ delete)\n"
      register: menu_vm

    - pause:
        prompt: "\nIn welke omgeving wilt u de VM aannmaken, aanpassen of verwijderen? \n \n- ontwikkel  (typ ontwikkel) \n- test       (typ test) \n- acceptatie (typ acceptatie) \n- productie  (typ productie)\n"
      register: menu_env

    - pause:
        prompt: "\nOp welke platform wilt u de VM aannmaken, aanpassen of verwijderen? \n \n- VMWare (typ vmware) \n- Azure  (typ azure) \n- AWS    (typ aws)\n"
      register: menu_platform

    - pause:
        prompt: "\nWat voor flavor heeft de VM? \n \n- 128MB RAM, 1 core, 10GB disk (typ micro.1) \n- 256MB RAM, 1 core, 15GB disk (typ micro.2) \n- 512MB RAM, 1 core, 20GB disk (typ small.1)\n"
      register: menu_flavor
      when: menu_vm.user_input == 'create'

    - pause:
        prompt: "\nHoeveel instanties wilt u hebben?\n"
      register: menu_instances 
      when: menu_vm.user_input == 'create' 

    - name: Setting the facts that the client has given
      set_fact:
        voornaam: "{{ menu_voornaam.user_input|lower }}"
        achternaam: "{{ menu_achternaam.user_input|lower }}"
        bedrijfsnaam: "{{ menu_bedrijfsnaam.user_input|lower }}"
        omgeving: "{{ menu_env.user_input }}"
        platform: "{{ menu_platform.user_input|default('vmware') }}"
        flavor: "{{ menu_flavor.user_input|default('n.v.t.') }}"
        operation: "{{ menu_vm.user_input }}"
        aantal_instanties: "{{ menu_instances.user_input|default('0') }}"
        final_vm_list: []
        final_vm_created: []
        yes_to_all_vm_delete: 'nee'

    - pause:
        prompt: "\nU heeft de volgende informatie ingevoerd, is dit correct (typ ja of nee): \n\nVoornaam: {{ voornaam }} \nAchternaam: {{ achternaam }} \nBedrijfsnaam: {{ bedrijfsnaam }} \nOmgeving: {{ omgeving }} \nPlatform: {{ platform }} \nFlavor: {{ flavor }} \nActie: {{ operation }} VM \nAantal instanties: {{ aantal_instanties }}\n"
      register: final_information_acc

    - fail:
        msg: U heeft nee ingevuld. Voer de Orchestrator opnieuw uit.
      when: final_information_acc.user_input == 'nee'

    - name: Include vars
      include_vars: '{{ item }}'
      loop:
        - './vars/env/all'
        - './vars/env/{{ omgeving }}'
        - './vars/flavors/{{ flavor }}'

    - name: Set fact of inventory group name
      set_fact:
        inventory_group_name_web: '{{ bedrijfsnaam }}_web_{{ omgeving }}'
        inventory_group_name_db: '{{ bedrijfsnaam }}_db_{{ omgeving }}'
        inventory_group_name_lb: '{{ bedrijfsnaam }}_lb_{{ omgeving }}'
  
    - name: Create list of web virtual machines that belong to customer
      set_fact:
        final_vm_list: '{{ final_vm_list + [hostvars[item]["inventory_hostname_short"]] }}'
      loop: '{{ groups[inventory_group_name_web] }}'
      ignore_errors: True

    - name: Create list of db virtual machines that belong to customer
      set_fact:
        final_vm_list: '{{ final_vm_list + [hostvars[item]["inventory_hostname_short"]] }}'
      loop: '{{ groups[inventory_group_name_db] }}'
      ignore_errors: True

    - name: Create list of db virtual machines that belong to customer
      set_fact:
        final_vm_list: '{{ final_vm_list + [hostvars[item]["inventory_hostname_short"]] }}'
      loop: '{{ groups[inventory_group_name_lb] }}'
      ignore_errors: True

    - pause:
        prompt: "Welke rol heeft VM {{ item }}?: \n\n- webserver (typ web) \n- database  (typ db) \n- load balancer  (typ lb) \n"
      register: vm_asked_questions
      with_sequence: count='{{ aantal_instanties }}'
      when: operation == 'create'

    - pause:
        prompt: "Wilt u alle servers verwijderen voor bedrijf: {{ bedrijfsnaam }} in omgeving: {{ omgeving }}? (typ ja of nee)"
      register: yes_to_all_vm_delete
      when: operation == 'delete'

    - name: Set yes_to_all_vm_delete fact if defined
      set_fact:
        yes_to_all_vm_delete: '{{ yes_to_all_vm_delete.user_input }}'
      when: yes_to_all_vm_delete.user_input is defined and operation == 'delete'

    - fail:
        msg: Er zijn geen virtuele machines voor het bedrijf '{{ bedrijfsnaam }}' volgens onze gegevens. Voer de Orchestrator opnieuw uit.
      when: (final_vm_list == [] and operation == 'delete') or (final_vm_list == [] and operation == 'modify')

    - pause:
        prompt: "Welke VM wilt u aanpassen of verwijderen?:\n\n{{ final_vm_list|to_nice_yaml }}\n"
      register: vm_to_modify
      when: operation == 'modify' or (operation == 'delete' and yes_to_all_vm_delete == 'nee')

    - name: Set default fact for '{{ operation }}' VM
      set_fact:
        final_vm_list: ['{{ vm_to_modify.user_input }}']
      when: operation == 'modify' or (vm_to_modify.user_input is defined and operation == 'delete')

    - pause:
        prompt: "Wat moet aangepast worden?:\n- Naam van de VM   (typ naam) \n- aantal CPU cores (typ cpu) \n- aantal memory    (typ memory)\n"
      register: what_to_modify
      when: operation == 'modify'

    - pause:
        prompt: "Hoe moet de nieuwe VM heten?\n"
      register: new_vm_name_ts
      when: operation == 'modify' and what_to_modify.user_input == 'naam'

    - pause:
        prompt: "Hoeveel CPU cores moet de VM krijgen?\n"
      register: cpu_cores
      when: operation == 'modify' and what_to_modify.user_input == 'cpu'

    - pause:
        prompt: "Hoeveel memory (in MB) moet de VM krijgen?\n"
      register: memory_mb
      when: operation == 'modify' and what_to_modify.user_input == 'memory'
      
    - name: Run operation create 
      include: "./playbooks/{{ platform }}/vm/create.yml"
      with_sequence: count='{{ vm_asked_questions.results }}'
      when: operation == 'create'
      vars:
        rol: '{{ item.user_input }}'

    - name: Run operation modify 
      include: "./playbooks/{{ platform }}/vm/modify.yml"
      when: operation == 'modify'
      vars:
        hostname: '{{ vm_to_modify.user_input }}'
        cpu: "{{ cpu_cores.user_input|default('nee') }}"
        memory: "{{ memory_mb.user_input|default('nee') }}"
        new_vm_name: "{{ new_vm_name_ts.user_input|default('nee') }}"
        old_fqdn: '{{ vm_to_modify.user_input }}.{{ domain }}'

    - name: Run operation delete 
      include: "./playbooks/{{ platform }}/vm/delete.yml"
      loop: '{{ final_vm_list }}'
      when: (operation == 'delete' and yes_to_all_vm_delete == 'ja') or (operation == 'delete' and vm_to_modify != '')

    - meta: refresh_inventory

- name: Configure the database servers
  hosts: "{{ hostvars['localhost']['bedrijfsnaam'] }}_db_{{ hostvars['localhost']['omgeving'] }}"
  become: True
  vars:
    bedrijfsnaam: "{{ hostvars['localhost']['bedrijfsnaam'] }}"
    omgeving: "{{ hostvars['localhost']['omgeving'] }}"
  roles:
    - db

- name: Configure the web servers
  hosts: "{{ hostvars['localhost']['bedrijfsnaam'] }}_web_{{ hostvars['localhost']['omgeving'] }}"
  become: True
  vars:
    bedrijfsnaam: "{{ hostvars['localhost']['bedrijfsnaam'] }}"
    omgeving: "{{ hostvars['localhost']['omgeving'] }}"
  roles:
    - web
    - php

- name: Configure the LB servers
  hosts: "{{ hostvars['localhost']['bedrijfsnaam'] }}_lb_{{ hostvars['localhost']['omgeving'] }}"
  become: True
  vars:
    bedrijfsnaam: "{{ hostvars['localhost']['bedrijfsnaam'] }}"
    omgeving: "{{ hostvars['localhost']['omgeving'] }}"
  roles:
    - lb